if(window.mermaid){mermaid.initialize({startOnLoad:false,securityLevel:'strict',theme:'base',themeVariables:{primaryColor:'#e8f0e9',primaryTextColor:'#244d34',primaryBorderColor:'#9ab29f',lineColor:'#7b877d',secondaryColor:'#f6f7f4',tertiaryColor:'#ffffff',fontFamily:'Inter'}});}
let course=[];let currentM=0,currentL=0;const key='ia-pratique-v3-progress';let progress=JSON.parse(localStorage.getItem(key)||'{}');
Promise.all(Array.from({length:12},(_,i)=>fetch(i===0?'module-01-v4.json':`module-${String(i+1).padStart(2,'0')}.json`).then(r=>r.json()))).then(data=>{course=data;init()}).catch(err=>{console.error(err);document.body.innerHTML='<p style="padding:30px">Impossible de charger le contenu du cours.</p>'});
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function paragraphs(t){return String(t||'').trim().split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p.trim())}</p>`).join('')}
function doneKey(m,l){return `${m}-${l}`}function isDone(m,l){return !!progress[doneKey(m,l)]}
function init(){const total=course.reduce((a,m)=>a+m.lessons.length,0);document.getElementById('lessonTotal').textContent=`${total} leçons`;renderRail();renderModules();updateProgress()}
function renderRail(){document.getElementById('railModules').innerHTML=course.map((m,i)=>`<button class="railModule" onclick="openModule(${i})"><span class="num">${i+1}</span><span class="railTitle">${esc(m.title)}</span><span class="railArrow">›</span></button>`).join('')}
function renderModules(filter=''){const q=filter.trim().toLowerCase(),el=document.getElementById('moduleGrid');el.innerHTML=course.map((m,i)=>({m,i})).filter(x=>!q||x.m.title.toLowerCase().includes(q)||(x.m.description||x.m.intro||'').toLowerCase().includes(q)).map(({m,i})=>{const done=m.lessons.filter((_,j)=>isDone(i,j)).length;return `<article class="moduleCard"><div class="cardTop"><span class="badge">${String(i+1).padStart(2,'0')}</span><span class="count">${m.lessons.length} leçons</span></div><h3>${esc(m.title)}</h3><p>${esc(m.description||m.intro||'')}</p><div class="cardFoot"><span class="doneText">${done}/${m.lessons.length} terminées</span><button class="openBtn" onclick="openModule(${i})">Voir les leçons →</button></div></article>`}).join('')||'<p>Aucun module trouvé.</p>'}
function filterModules(v){renderModules(v);document.getElementById('modules').scrollIntoView({behavior:'smooth'})}
function showHome(){document.getElementById('homeWrap').style.display='grid';document.getElementById('lessonView').classList.remove('show');renderRail();renderModules(document.getElementById('search')?.value||'');updateProgress();window.scrollTo({top:0,behavior:'smooth'})}
function openModule(i){currentM=i;currentL=0;openLesson(i,0)}
function startCourse(){for(let i=0;i<course.length;i++){for(let j=0;j<course[i].lessons.length;j++){if(!isDone(i,j)){openLesson(i,j);return}}}openLesson(0,0)}
function openLesson(m,l){currentM=m;currentL=l;document.getElementById('homeWrap').style.display='none';document.getElementById('lessonView').classList.add('show');renderSidebar();renderArticle();window.scrollTo({top:0,behavior:'smooth'})}
function renderSidebar(){const m=course[currentM];document.getElementById('sidebar').innerHTML=`<button class="backBtn" onclick="showHome()">← Retour au sommaire</button><div class="sideTitle">${esc(m.title)}</div>${m.lessons.map((x,j)=>`<button class="lessonLink ${j===currentL?'active':''} ${isDone(currentM,j)?'done':''}" onclick="openLesson(${currentM},${j})">${j+1}. ${esc(x.title)}</button>`).join('')}`}
function lessonContent(l){if(Array.isArray(l.sections)&&l.sections.length){return `<div class="lessonSections">${l.sections.map(s=>`<section class="lessonSection"><h3>${esc(s.title)}</h3><div class="prose">${paragraphs(s.body)}</div></section>`).join('')}</div>`}return `<div class="prose">${paragraphs(l.content)}</div>`}
function keypoints(l){return Array.isArray(l.keypoints)&&l.keypoints.length?`<div class="takeaways"><h3>À retenir</h3><ul>${l.keypoints.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}
function diagramBlock(l){return l.diagram?`<section class="visualBlock"><div class="visualTitle">${esc(l.diagram.title||'Schéma')}</div><div class="diagramShell"><div id="lessonDiagram" class="diagramCanvas"></div></div></section>`:''}
function correctionBlock(l){return l.correction?`<details class="correction"><summary>Voir une correction possible</summary><div>${esc(l.correction)}</div></details>`:''}
function quizBlock(l){if(!Array.isArray(l.quiz)||!l.quiz.length)return'';return `<section class="quiz"><h3>Mini quiz</h3>${l.quiz.map((q,qi)=>`<div class="quizQ"><b>${qi+1}. ${esc(q.q)}</b>${q.options.map((o,oi)=>`<label class="quizOpt"><input type="radio" name="quiz-${currentM}-${currentL}-${qi}" value="${oi}"><span>${esc(o)}</span></label>`).join('')}<div class="quizResult" id="quiz-result-${qi}"></div></div>`).join('')}<button class="btn small" onclick="checkQuiz()">Corriger le quiz</button></section>`}
function interactiveBlock(l){if(!l.interactive)return'';return `<section class="interactive"><div class="interactiveHead"><b>Démo interactive</b><span>Manipule le concept</span></div><div class="interactiveBody">${interactiveHtml(l.interactive)}</div></section>`}
function interactiveHtml(type){
 if(type==='generation')return `<div class="stepFlow" id="genSteps"><div class="step">Prompt</div><div class="step">Tokenisation</div><div class="step">Modèle</div><div class="step">Probabilités</div><div class="step">Token suivant</div></div><div class="actions"><button class="btn primary small" onclick="runGenerationDemo()">Lancer une génération</button><button class="btn small" onclick="resetGenerationDemo()">Réinitialiser</button></div><div class="genOutput" id="genOutput">La sortie apparaîtra token après token.</div>`;
 if(type==='tokens')return `<div class="tokeninput"><input id="tokInput" value="RushLess supprime mes répétitions, mais garde la meilleure prise." oninput="updateTokenLab()"><button class="btn small" onclick="updateTokenLab()">Analyser</button></div><div class="tokens" id="tokens"></div><div class="contextMeter"><div id="contextFill"></div></div><div class="labStats"><div class="labStat"><b id="tokCount">0</b><span>tokens approx.</span></div><div class="labStat"><b id="charCount">0</b><span>caractères</span></div><div class="labStat"><b id="inputCost">$0.0000</b><span>coût input estimé</span></div></div><div class="costGrid"><label>Prix input / 1M tokens ($)<input id="inputPrice" type="number" step="0.1" value="3" oninput="updateTokenLab()"></label><label>Taille de contexte illustrative<input id="ctxMax" type="number" value="128000" oninput="updateTokenLab()"></label></div><p style="font-size:11px;color:#858a85;margin-bottom:0">Le découpage est volontairement approximatif : chaque modèle possède son tokenizer.</p>`;
 if(type==='learning-modes')return `<div class="modeTabs"><button class="active" onclick="showMode('training',this)">Training</button><button onclick="showMode('inference',this)">Inference</button><button onclick="showMode('rag',this)">RAG</button><button onclick="showMode('fine',this)">Fine-tuning</button></div><div class="modePanel" id="modePanel"></div>`;
 if(type==='router')return `<div class="taskTabs"><button class="active" onclick="routeTask('json',this)">Extraire du JSON</button><button onclick="routeTask('bug',this)">Bug d’architecture</button><button onclick="routeTask('stock',this)">Détecter un stock Smash</button><button onclick="routeTask('repeat',this)">Comprendre une reprise</button></div><div class="modePanel" id="routeText"></div><div class="routeResult"><div class="routeMetric"><span>Solution</span><b id="routeSolution">—</b></div><div class="routeMetric"><span>Coût relatif</span><b id="routeCost">—</b></div><div class="routeMetric"><span>Latence relative</span><b id="routeLatency">—</b></div></div>`;
 if(type==='reliability')return `<div class="stepFlow" id="reliabilitySteps"><div class="step">LLM</div><div class="step">JSON</div><div class="step">Schéma</div><div class="step">Règles métier</div><div class="step">Action</div></div><div class="simTabs" style="margin-top:14px"><button onclick="simulateReliability(true)">Simuler une réponse valide</button><button onclick="simulateReliability(false)">Simuler une erreur</button></div><div class="pipelineResult" id="pipelineResult">Choisis un scénario.</div>`;
 return'';
}
function renderArticle(){const m=course[currentM],l=m.lessons[currentL];const prev=currentL>0?`<button onclick="openLesson(${currentM},${currentL-1})">← Précédent</button>`:(currentM>0?`<button onclick="openLesson(${currentM-1},${course[currentM-1].lessons.length-1})">← Module précédent</button>`:'<span></span>');const next=currentL<m.lessons.length-1?`<button onclick="openLesson(${currentM},${currentL+1})">Suivant →</button>`:(currentM<course.length-1?`<button onclick="openLesson(${currentM+1},0)">Module suivant →</button>`:'<span></span>');document.getElementById('article').innerHTML=`<div class="crumb">Module ${currentM+1} • Leçon ${currentL+1}</div><h2>${esc(l.title)}</h2><div class="meta">${esc(l.duration||'')} • ${esc(m.title)}</div>${l.objective?`<div class="objective"><b>Objectif</b>${esc(l.objective)}</div>`:''}${lessonContent(l)}${keypoints(l)}${diagramBlock(l)}${interactiveBlock(l)}${l.example?`<div class="callout"><b>Exemple concret</b><br>${esc(l.example)}</div>`:''}${l.exercise?`<div class="exercise"><h3>À toi de jouer</h3><p>${esc(l.exercise)}</p></div>`:''}${correctionBlock(l)}${quizBlock(l)}<div class="articleNav"><div>${prev}</div><button class="complete" onclick="toggleDone()">${isDone(currentM,currentL)?'✓ Leçon terminée':'Marquer comme terminée'}</button><div>${next}</div></div>`;afterLessonRender(l)}
function afterLessonRender(l){if(l.diagram){const el=document.getElementById('lessonDiagram');el.textContent=l.diagram.code;if(window.mermaid){el.classList.add('mermaid');mermaid.run({nodes:[el]}).catch(console.error)}else{el.style.whiteSpace='pre-wrap';el.style.fontFamily='monospace';el.style.fontSize='12px'}}if(l.interactive==='tokens')setTimeout(updateTokenLab,0);if(l.interactive==='learning-modes')setTimeout(()=>showMode('training'),0);if(l.interactive==='router')setTimeout(()=>routeTask('json'),0)}
function toggleDone(){const k=doneKey(currentM,currentL);progress[k]=!progress[k];if(!progress[k])delete progress[k];localStorage.setItem(key,JSON.stringify(progress));renderSidebar();renderArticle();updateProgress()}
function updateProgress(){if(!course.length)return;const total=course.reduce((a,m)=>a+m.lessons.length,0),done=course.reduce((a,m,i)=>a+m.lessons.filter((_,j)=>isDone(i,j)).length,0),pct=Math.round(done/total*100);const p=document.getElementById('progressPct');if(p)p.textContent=`${pct}%`;const f=document.getElementById('progressFill');if(f)f.style.width=`${pct}%`;const t=document.getElementById('progressText');if(t)t.textContent=`${done} leçon${done>1?'s':''} terminée${done>1?'s':''}`;const c=document.getElementById('progressCount');if(c)c.textContent=`${done} / ${total}`}
function runGenerationDemo(){resetGenerationDemo();const steps=[...document.querySelectorAll('#genSteps .step')],out=document.getElementById('genOutput');const tokens=['RushLess',' analyse',' le',' contexte',',',' propose',' une',' décision',',',' puis',' le',' code',' la',' valide','.'];out.textContent='';if(window.gsap){const tl=gsap.timeline();steps.forEach((s,i)=>tl.to(s,{duration:.16,onStart:()=>{steps.forEach(x=>x.classList.remove('active'));s.classList.add('active')}},i*.22));tokens.forEach((t,i)=>tl.call(()=>{out.textContent+=t},[],1.25+i*.08));tl.call(()=>steps.forEach(x=>x.classList.remove('active')))}else{tokens.forEach(t=>out.textContent+=t)}}
function resetGenerationDemo(){document.querySelectorAll('#genSteps .step').forEach(x=>x.classList.remove('active'));const o=document.getElementById('genOutput');if(o)o.textContent='La sortie apparaîtra token après token.'}
function approxTokens(text){return text.match(/[\p{L}\p{N}]+|[^\s\p{L}\p{N}]/gu)||[]}
function updateTokenLab(){const input=document.getElementById('tokInput');if(!input)return;const parts=approxTokens(input.value),count=parts.length,price=Math.max(0,Number(document.getElementById('inputPrice')?.value||0)),max=Math.max(1,Number(document.getElementById('ctxMax')?.value||128000));document.getElementById('tokens').innerHTML=parts.map(x=>`<span class="token">${esc(x)}</span>`).join('');document.getElementById('tokCount').textContent=count;document.getElementById('charCount').textContent=input.value.length;document.getElementById('inputCost').textContent=`$${(count/1e6*price).toFixed(6)}`;document.getElementById('contextFill').style.width=`${Math.min(100,count/max*100)}%`}
const modes={training:{title:'Training',text:'Le modèle apprend sur un grand corpus et ses paramètres sont modifiés. C’est la phase lourde qui crée les capacités générales.'},inference:{title:'Inference',text:'Tu envoies un contexte à un modèle déjà entraîné. Les paramètres ne sont pas réécrits par ta requête.'},rag:{title:'RAG',text:'Ton application cherche d’abord les passages pertinents dans une source externe, puis les ajoute au contexte avant la génération.'},fine:{title:'Fine-tuning',text:'On ajuste certains paramètres à partir d’exemples spécialisés pour modifier ou stabiliser un comportement.'}};
function showMode(k,btn){document.querySelectorAll('.modeTabs button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const m=modes[k],p=document.getElementById('modePanel');if(p){p.innerHTML=`<b>${m.title}</b><br>${m.text}`;if(window.gsap)gsap.fromTo(p,{opacity:.35,y:6},{opacity:1,y:0,duration:.25})}}
const routes={json:{text:'Extraire trois champs structurés est généralement une tâche simple si le texte est clair.',solution:'Petit LLM / modèle rapide',cost:'Faible',latency:'Faible'},bug:{text:'Un bug d’architecture ambigu demande de suivre plusieurs dépendances et hypothèses.',solution:'LLM de raisonnement',cost:'Moyen / élevé',latency:'Moyenne'},stock:{text:'Détecter une perte de stock est d’abord un problème visuel et temporel, pas un problème de langage.',solution:'Vision / CV + règles',cost:'Faible à moyen',latency:'Faible'},repeat:{text:'Décider si deux formulations sont deux prises du même passage est une tâche sémantique et contextuelle.',solution:'LLM + validation locale',cost:'Moyen',latency:'Moyenne'}};
function routeTask(k,btn){document.querySelectorAll('.taskTabs button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const r=routes[k];const t=document.getElementById('routeText');if(t)t.textContent=r.text;document.getElementById('routeSolution').textContent=r.solution;document.getElementById('routeCost').textContent=r.cost;document.getElementById('routeLatency').textContent=r.latency;if(window.gsap)gsap.fromTo('.routeMetric',{opacity:.4,y:5},{opacity:1,y:0,duration:.25,stagger:.05})}
function simulateReliability(valid){const steps=[...document.querySelectorAll('#reliabilitySteps .step')],result=document.getElementById('pipelineResult');steps.forEach(x=>x.classList.remove('active'));result.className='pipelineResult';result.textContent='';let stop=valid?5:4;if(window.gsap){const tl=gsap.timeline();for(let i=0;i<stop;i++){tl.call(()=>{steps.forEach(x=>x.classList.remove('active'));steps[i].classList.add('active')},[],i*.34)}tl.call(()=>{steps.forEach(x=>x.classList.remove('active'));if(valid){result.textContent='✓ Toutes les validations passent : l’action peut être appliquée.';result.classList.add('statusGood')}else{result.textContent='✕ Règle métier rejetée : les IDs ne sont pas contigus. L’action est bloquée.';result.classList.add('statusBad');steps[3].classList.add('active')}},[],stop*.34)}else{result.textContent=valid?'✓ Action autorisée.':'✕ Action bloquée.'}}
function checkQuiz(){const l=course[currentM].lessons[currentL];if(!l.quiz)return;l.quiz.forEach((q,qi)=>{const checked=document.querySelector(`input[name="quiz-${currentM}-${currentL}-${qi}"]:checked`),res=document.getElementById(`quiz-result-${qi}`);if(!checked){res.textContent='Choisis une réponse.';res.className='quizResult bad';return}const ok=Number(checked.value)===q.answer;res.textContent=(ok?'✓ Correct. ':'✕ Pas tout à fait. ')+(q.explanation||'');res.className=`quizResult ${ok?'ok':'bad'}`})}